### ISSUE TITLE
Recommended ammend for install process.

### ISSUE THREAD

**Issue by erenfro** [armandg/sol3rd#2]
pip can break things by simply not working together with package managers, including Solus's.

I'd recommend adding to the documentation to install Solus-included packages for python modules that already exist in solus.

sudo eopkg it python-beautifulsoup4 python-html5lib python-colorama python-webencodings python-requests python-idna python-certifi  python-six python-urllib3

This will reduce potential damage caused by pip as the only things remaining are b4 and sol3rd itself.
Other than that, have you tried to get this packaged in Solus itself? :)

**Comment by geirawsm** [comment]
First off, I'm a newbie when it comes to packaging, I learned some of it nearly two days ago, so bear with me if there are some things I misunderstand.

I have no idea how pip and eopkg takes notice of each others installation of modules. How can I make setup.py get the necessary modules from eopkg instead of pip?
And how can this be controlled in an upgrade of sol3rd?

No I haven't tried getting it into Solus. since the new edition of the package manager will support this eventually, I figured there was no need. Also, again - I _just_ learned packaging ;D

**Comment by erenfro** [comment]
pip and eopkg don't know what each other is doing, but what can be done is to eopkg all the that I said, document that, and then pip can work to install just the remaining depends that don't currently conflict, which is b4 and sol3rd, just by pip installing it per normal afterwards.

Basically primarily, I'm recommending a README update to, first do:

```
sudo eopkg it python-beautifulsoup4 python-html5lib python-colorama python-webencodings python-requests python-idna python-certifi python-six python-urllib3
```

Then do:

```
pip install sol3rd
```

To reduce conflicting packages for python and solus itself. :)

(Afterall, eopkg itself is python, so pip could stop its functionality if it installed, replaced, updated, anything that eokpkg depends on)

**Comment by geirawsm** [comment]
Thanks, I'll add this to README.

**Comment by geirawsm** [comment]
Added in dcfb7cddf300a97acaea09d39ccf476a8352c5b7.
